test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
digitalocean:
  service: S3
  endpoint: https://sfo3.digitaloceanspaces.com
  access_key_id: "<%= ENV.fetch('SPACES_KEY') %>"
  secret_access_key: "<%= ENV.fetch('SPACES_SECRET') %>"
  region: sfo3
  bucket: gravsgoods
